# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IntegrePol2CPos <- function(x, a0, b0, c0) {
    .Call('_SpectrumSyphilis_IntegrePol2CPos', PACKAGE = 'SpectrumSyphilis', x, a0, b0, c0)
}

VectIntegreSegPol2 <- function(xpars, vectx, frestrknots) {
    .Call('_SpectrumSyphilis_VectIntegreSegPol2', PACKAGE = 'SpectrumSyphilis', xpars, vectx, frestrknots)
}

VectIntegrePol2CPos <- function(xpars, vectx, frestrknots) {
    .Call('_SpectrumSyphilis_VectIntegrePol2CPos', PACKAGE = 'SpectrumSyphilis', xpars, vectx, frestrknots)
}

